version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:
    environment:
      - CODECOV_TOKEN: '0ba5cbfb-c75d-4e83-81be-b594366f1166'
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - store_artifacts:
          path : target
      - codecov/upload:
          file : target

workflows:
  sample: 
    jobs:
      - build-and-test
